from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns
from restapi import project, requirement, feature, testplan, testsuite,testcase,dpdk
from restapi import testexecution, suiteresult, caseresult, app, perf_dpdk,vhostscsi

urlpatterns = [
    # maintain base data
    url(r'^project/$', project.ProjectList.as_view()),
    url(r'^(?P<project>.*)/requirement_type/$',
        requirement.RequirementTypeList.as_view()),
    url(r'^(?P<project>.*)/requirement_type/(?P<pk>[0-9]+)/$',
        requirement.RequirementTypeDetail.as_view()),
    url(r'^(?P<project>.*)/requirement/$',
        requirement.RequirementList.as_view()),
    url(r'^(?P<project>.*)/requirement/(?P<pk>[0-9]+)/$',
        requirement.RequirementDetail.as_view()),
    url(r'^(?P<project>.*)/feature_component/$',
        feature.FeatureComponentList.as_view()),
    url(r'^(?P<project>.*)/feature_component/(?P<pk>[0-9]+)/$',
        feature.FeatureComponentDetail.as_view()),
    url(r'^(?P<project>.*)/feature/$',
        feature.FeatureList.as_view()),
    url(r'^(?P<project>.*)/feature/(?P<pk>[0-9]+)/$',
        feature.FeatureDetail.as_view()),
    url(r'^(?P<project>.*)/testplan_category/$',
        testplan.TestplanCategoryList.as_view()),
    url(r'^(?P<project>.*)/testplan_category/(?P<pk>[0-9]+)/$',
        testplan.TestplanCategoryDetail.as_view()),
    url(r'^(?P<project>.*)/testplan/$', testplan.TestplanList.as_view()),
    url(r'^(?P<project>.*)/testplan/(?P<pk>[0-9]+)/$',
        testplan.TestplanDetail.as_view()),
    url(r'^(?P<project>.*)/testsuite_subsystem/$',
        testsuite.TestsuiteSubsystemList.as_view()),
    url(r'^(?P<project>.*)/testsuite_subsystem/(?P<pk>[0-9]+)/$',
        testsuite.TestsuiteSubsystemDetail.as_view()),
    url(r'^(?P<project>.*)/testsuite/$', testsuite.TestsuiteList.as_view()),
    url(r'^(?P<project>.*)/testsuite/(?P<pk>[0-9]+)/$',
        testsuite.TestsuiteDetail.as_view()),
    url(r'^(?P<project>.*)/testcase_type/$',
        testcase.TestcaseTypeList.as_view()),
    url(r'^(?P<project>.*)/testcase_type/(?P<pk>[0-9]+)/$',
        testcase.TestcaseTypeDetail.as_view()),
    url(r'^(?P<project>.*)/testcase/$',
        testcase.TestcaseList.as_view()),
    url(r'^(?P<project>.*)/testcase/(?P<pk>[0-9]+)/$',
        testcase.TestcaseDetail.as_view()),
    url(r'^(?P<project>.*)/testexecution_os/$',
        testexecution.TestexecutionOsList.as_view()),
    url(r'^(?P<project>.*)/testexecution_os/(?P<pk>[0-9]+)/$',
        testexecution.TestexecutionOsDetail.as_view()),
    url(r'^(?P<project>.*)/testexecution_platform/$',
        testexecution.TestexecutionPlatformList.as_view()),
    url(r'^(?P<project>.*)/testexecution_platform/(?P<pk>[0-9]+)/$',
        testexecution.TestexecutionPlatformDetail.as_view()),
    url(r'^(?P<project>.*)/testexecution/$',
        testexecution.TestexecutionList.as_view()),
    url(r'^(?P<project>.*)/testexecution/(?P<pk>[0-9]+)/$',
        testexecution.TestexecutionDetail.as_view()),
    url(r'^(?P<project>.*)/testexecution_suite_result/(?P<pk>[0-9]+)/$',
        suiteresult.TestexecutionSuiteResultDetail.as_view()),
	############ I defined API url #########################
    url(r'^(?P<project>.*)/testexecution_suite_result/$',
        suiteresult.TestexecutionSuiteResultDetail.as_view()),
	#########################################################
    #url(r'^(?P<project>.*)/testsuite_testcase/(?P<pk>[0-9]+)/$',
        #suiteresult.TestsuiteTestcaseDetail.as_view()),
    #url(r'^(?P<project>.*)/suiteresult_caseresult/(?P<pk>[0-9]+)/$',
        #suiteresult.TestSuiteResultTestcaseResultDetail.as_view()),
    url(r'^(?P<project>.*)/testcase_result/$', caseresult.TestcaseResult.as_view()),
    url(r'^(?P<project>.*)/testcase_result/(?P<pk>[0-9]+)/$',
        caseresult.TestcaseResultDetail.as_view()),
    url(r'^(?P<project>.*)/app/$', app.AppList.as_view()),
    url(r'^(?P<project>.*)/app/(?P<pk>[0-9]+)/$', app.AppDetail.as_view()),
    url(r'^(?P<project>.*)/app_attr/$', app.AppAttrList.as_view()),
    url(r'^(?P<project>.*)/app_attr/(?P<pk>[0-9]+)/$', app.AppAttrDetail.as_view()),
    url(r'^(?P<project>.*)/testexecution_perf_suite_result/(?P<pk>[0-9]+)/$',
        suiteresult.TestexecutionPerfSuiteResultDetail.as_view()),
    url(r'^(?P<project>.*)/perf_suiteresult_caseresult/(?P<pk>[0-9]+)/$',
        suiteresult.PerTestsuiteResultTestcaseResultPK.as_view()),
    url(r'^(?P<project>.*)/perf_caseresult_detailresult/(?P<pk>[0-9]+)/$',
        suiteresult.PerTestcaseResultTestcaseDetailResultPK.as_view()),
    url(r'^(?P<project>.*)/perf_testcase_result/$', caseresult.PerTestcaseResult.as_view()),
    url(r'^(?P<project>.*)/perf_testcase_result/(?P<pk>[0-9]+)/$',
        caseresult.PerTestcaseResultPK.as_view()),
    url(r'^(?P<project>.*)/perf_testcase_result_detail/$',
        caseresult.PerTestcaseResultDetail.as_view()),
    url(r'^(?P<project>.*)/perf_testcase_result_detail/(?P<pk>[0-9]+)/$',
        caseresult.PerTestcaseResultDetailPK.as_view()),

    # Just for DPDK performance test
    url(r'^(?P<project>.*)/perf_dpdk_suiteresult_caseresult/(?P<pk>[0-9]+)/$',
        perf_dpdk.PerDPDKTestsuiteResultTestcaseResultPK.as_view()),
    url(r'^(?P<project>.*)/perf_dpdk_caseresult_detailresult/(?P<pk>[0-9]+)/$',
        perf_dpdk.PerDPDKTestcaseResultTestcaseDetailResultPK.as_view()),
    url(r'^(?P<project>.*)/perf_dpdk_testcase_result/(?P<pk>[0-9]+)/$',
        perf_dpdk.PerDPDKTestcaseResultPK.as_view()),
    url(r'^(?P<project>.*)/perf_dpdk_testcase_result_detail/$',
        perf_dpdk.PerDPDKTestcaseResultDetail.as_view()),
    url(r'^(?P<project>.*)/perf_dpdk_testcase_result_detail/(?P<pk>[0-9]+)/$',
        perf_dpdk.PerDPDKTestcaseResultDetailPK.as_view()),
    url(r'^(?P<project>.*)/myresult/(?P<pk>[0-9]+)/$',
        suiteresult.MySuiteResultDetail.as_view()),
    #url(r'^(?P<project>.*)/nicresult/(?P<pk>[0-9]+)/$',
    url(r'^(?P<project>.*)/nicresult/$',
        suiteresult.NicPerfTableDetail.as_view()),
    url(r'^(?P<project>.*)/testrecord/(?P<pk>[0-9]+)/$',
        suiteresult.TestRecordTableDetail.as_view()),
############DpdkTestRecord################
    url(r'^(?P<project>.*)/dpdk_testrecord/(?P<pk>[0-9]+)/$',
        dpdk.DpdkTestRecordTableDetail.as_view()),
##########################################
    url(r'^(?P<project>.*)/cpu_type/(?P<pk>[0-9]+)/$',
    #url(r'^(?P<project>.*)/cpu_type/$',
        suiteresult.CpuTypeDetail.as_view()),
    url(r'^(?P<project>.*)/cpuinfo/(?P<pk>[0-9]+)/$',
        suiteresult.CpuInfoDetail.as_view()),



    url(r'^(?P<project>.*)/nic_name/(?P<pk>[0-9]+)/$',
        suiteresult.NicNameDetail.as_view()),

    url(r'^(?P<project>.*)/cpuinfo/(?P<pk>[0-9]+)/$',
        suiteresult.CpuInfoDetail.as_view()),

    url(r'^(?P<project>.*)/firmware/(?P<pk>[0-9]+)/$',
        suiteresult.FirmwareDetail.as_view()),
    url(r'^(?P<project>.*)/case_type/(?P<pk>[0-9]+)/$',
        suiteresult.CaseTypeDetail.as_view()),
    url(r'^(?P<project>.*)/nic_perf/(?P<pk>[0-9]+)/$',
        suiteresult.NicPerfTableDetail.as_view()),
    url(r'^(?P<project>.*)/singel_core/(?P<pk>[0-9]+)/$',
        suiteresult.SingleCorePerfTableDetail.as_view()),
    url(r'^(?P<project>.*)/spdk_perf_result/(?P<pk>[0-9]+)/$',
        suiteresult.SpdkPerfResultDetail.as_view()),
    url(r'^(?P<project>.*)/rw_method/(?P<pk>[0-9]+)/$',
        suiteresult.RwMethodDetail.as_view()),
    url(r'^(?P<project>.*)/queue_depth/(?P<pk>[0-9]+)/$',
        suiteresult.Queue_depthDetail.as_view()),
    url(r'^(?P<project>.*)/io_size/(?P<pk>[0-9]+)/$',
        suiteresult.io_sizeDetail.as_view()),
    url(r'^(?P<project>.*)/spdk_trend_result/(?P<pk>[0-9]+)/$',
        suiteresult.SpdkTrendResultDetail.as_view()),

    #Nvme-Driver url:
    url(r'^(?P<project>.*)/nvme_driver_trend_result/(?P<pk>[0-9]+)/$',
        suiteresult.NvmeDriverResultDetail.as_view()),

    #Vhost-Scsi url:
    url(r'^(?P<project>.*)/vhost_scsi_trend_result/(?P<pk>[0-9]+)/$',
    #url(r'^(?P<project>.*)/vhost_scsi_trend_result/$',
        vhostscsi.VhostScsiTrendResultDetail.as_view()),
    url(r'^(?P<project>.*)/vhost_scsi_perf_result/(?P<pk>[0-9]+)/$',
        vhostscsi.VhostScsiPerfResultDetail.as_view()),

]

urlpatterns = format_suffix_patterns(urlpatterns)
